# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_other_file_type_menu_fix
project_short_description: Jupyterlab fix delivered as extension that fixes annoying
    issue where a non-standard type file (e.g. LICENSE or .gitignore or any other)
    doesn't have a standard menu, and the context menu that displays doesn't have
    refresh view command and doesn't properly show the menu items and doesn't highlight
    current hover over pointed item
python_name: jupyterlab_other_file_type_menu_fix
repository: ''
test: true

